import Head from 'next/head'
import Link from 'next/link'
export async function getStaticProps() {
    const res = await fetch('http://127.0.0.1:8000/api/books');
    const data = await res.json();
    console.log(json);
    return {
        props: {
            books: ['asdw']
        }
    }
}
const BookList = ({books}) => {
    return (
        <div>
            <Head>
                <title>Books App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <h1>Libros</h1>
            <ul>
                {/* {books.map(book =>(
                    <li>{book.title}</li>
                ))} */}
            </ul>
            <Link href="/libros/crear">Crear libro</Link>
        </div>
    );
}

export default BookList;